language: node_js
node_js:
  - node
install:
  - yarn global add codecov
  - yarn
script:
  - yarn lint
  - yarn format:check
  - yarn test --coverage --verbose
  - yarn build
  - git diff --exit-code --name-only
  - codecov
deploy:
  provider: npm
  email: se.mo.moosavi@gmail.com
  api_key:
    secure: N57RtcNlBYkG0KgZfSoVDe6nccGuEIm6t8kT2Bku2FABC53dQxt6QcVUM0BRLrPj41sUxMe8GMT42AJbiY38gyv2mgmqZmNE0csEpmBbEeXgkL/Lo3gcgiv79beGZyAQIGGj+q1igAQKFTE/ASdC+vIYBVVxaCTSPLhLa7Qpg1syy+Dclmr6coW6hAdfp/oLb5cali2seKwByzSPMkVTr1rO4I1B+KR/D+8uPJQgP/Gr98GIgfX1bOg8XxRnob7eTTOJXZlqQCGC1y12wppwgmrxVydiSRUl91ljI3Zw+X7rS3HX726JZu7A+LwT8CzTV76jpRVj1M/9GCDCpmKQAb8SUiufZ6jthZYg52JrpE2JLDDwHql0Pdmc41u/uiIukAxNuMI8rexYZe4nyoBe2ar43edq4TM3f8OLA7/OpFTGhG/FbvU3K5lFRe896N67mtsbtireWbKmWAZEMe28xQ/LDN2nseh9Mk/7zJcOAvCIULJ90VgvlzUsWY5xyrhR6/Ir7n6ISrjqfqXTMlYXWSlNEe6XX14y4V5MrrtljKtrvdEFe3wTy3SVJZH0bh+Akt+HEQ1sTJyQOVQ+r61A11BIwCayGXAQ22axw6sP17XwiAIqvKoOlrHpy39L9NE1KaOGkFGxndYRIG24/GvW8dOiP5vfSPxbi+PfnTlBlrM=
  skip_cleanup: true
  on:
    tags: true
    repo: forminator/react-wire
