language: node_js
node_js:
  - node
install:
  - yarn global add codecov
  - yarn
script:
  - yarn lint
  - yarn format:check
  - yarn test --coverage --verbose
  - yarn build
  - git diff --exit-code --name-only
  - codecov
deploy:
  provider: npm
  email: se.mo.moosavi@gmail.com
  api_key:
    secure: Rab/2NqD++D3FnvCKsQbLQHbFdZp7d8zCH9DGhQ2achHS4HdCKPiovcsZV2yZrhRJM5IetNhhmfa9fttREDJN31t6RTwHHSAEMjb2sI+8Qp1AS982F/Ght1K8eoH7YoBn+yKycnqQ5CG8JxzL2zHEp+9pGdEJYVxSgA+lv3/uqruAe9d/lTC7K5dJKqmFAaANfweqUNv5A97K83ttJtchEhsEjC1Uh/Y88tfhw9vgauEjMOhq8ybLE7ldAcS3cDMAZ4eNPX3CdfwZnvmt5g8Sy0KFarsd4T5dzKoDriccQO3wIpwvoaQPycuNb2jhvv7NmJtwrGye56XMvn4dskBPvxiBtRhzVlKy/wJ9UUZlG56rCg2FAIoaeJFmk1xZr77ZGx8bvbyEShhIsVuoZ/BMVNrS5Tez9ydu/iCDK2QdPR9c4vUvXAl3JzWssMFjL4Na01yyE6BqWWWoolAibnoY4Fbe1Br0MxWJZpvSwPKeMXJXOx0QKPsthPLR5+e77V89IOao9/PJbV4MDNhi1HG7mOvF+wC+hKclkyweqPV0ZWEeHAUc5+OoO0xYCfcnb5jUBOi/TExBr6yeLvMzdXdxLg1bcM7aktH2xpfsbrKIM69YWCI/2qqCk28l99AuqWkmQ+DNnrLeSm4gDrnpXEnekWGKfVZoUPOCOAj194d8Io=
  skip_cleanup: true
  on:
    tags: true
    repo: forminator/react-wire
